{
 "title": "01.OpenStack Dashboard",
 "description": "Openstack dashboard using the Openstack Exporter (https://github.com/Linaro/openstack-exporter)",
 "tags": [
  "openstack",
  "openstack-exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "인스턴스", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "인스턴스 상태",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  display_name AS metric,\n  CASE vm_state \n    WHEN 'active' THEN 1\n    WHEN 'stopped' THEN 0\n    WHEN 'error' THEN -1\n    WHEN 'paused' THEN 2\n    ELSE 3\n  END AS value\nFROM instances \nWHERE vm_state != 'deleted'\nORDER BY host, display_name"
    }
   ]
  },
  { "title": "서비스 상태", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "중지된 Nova 에이전트",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"enabled\"})-sum(openstack_nova_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Nova 에이전트 상태",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openstack_nova_agent_state{adminState=\"enabled\"}"
    }
   ]
  },
  {
   "title": "사용중인 Nova 에이전트",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "중지된 Cinder 에이전트",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(openstack_cinder_agent_state{adminState=\"enabled\"})-sum(openstack_cinder_agent_state{adminState=\"enabled\"}))"
    }
   ]
  },
  {
   "title": "Cinder 에이전트 상태",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "openstack_cinder_agent_state" }
   ]
  },
  {
   "title": "사용중인 Cinder 에이전트",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_cinder_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "중지된 Neutron 에이전트",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_neutron_agent_state{adminState=\"up\"})-sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  {
   "title": "Neutron 에이전트 상태",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "openstack_neutron_agent_state" }
   ]
  },
  {
   "title": "사용중인 Neutron 에이전트",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  { "title": "리소스 사용량", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "서버 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Neutron 상태",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_floating_ips) ",
     "legendFormat": "floating ips"
    },
    {
     "expr": "avg(openstack_neutron_networks)",
     "legendFormat": "networks"
    },
    {
     "expr": "avg(openstack_neutron_security_groups)",
     "legendFormat": "security groups"
    },
    { "expr": "avg(openstack_neutron_subnets)", "legendFormat": "subnets" }
   ]
  },
  {
   "title": "Keystone 상태",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(openstack_identity_projects)",
     "legendFormat": "projects"
    },
    { "expr": "avg(openstack_identity_users)", "legendFormat": "users" },
    { "expr": "avg(openstack_identity_groups)", "legendFormat": "groups" }
   ]
  },
  {
   "title": "인스턴스 개수",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_running_vms)",
     "legendFormat": "running vms"
    },
    { "expr": "sum(openstack_nova_total_vms)", "legendFormat": "total vms" }
   ]
  },
  {
   "title": "Cinder 볼륨, 스냅샷",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(openstack_cinder_volumes)", "legendFormat": "volumes" },
    {
     "expr": "avg(openstack_cinder_snapshots)",
     "legendFormat": "snapshots"
    }
   ]
  },
  {
   "title": "Glance 이미지",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(openstack_glance_images)", "legendFormat": "images" }
   ]
  }
 ]
}